bwa_index: ../../../annotations/GRCh38/bwa_index/GRCh38
picard_path: '/software/java/bin/java -jar -Xmx1800m /nfs/users/nfs_k/ka8/software/picard-tools-1.134/picard.jar'
chromosome_lengths: ../../../annotations/GRCh38/bt2-index/chromosome_lengths.txt
samples: [Mono_4983_1,Mono_4983_2,Mono_6792_1,Mono_6792_2,Mono_7256_1,Mono_7256_2]
